Added ability to pass username and password for Registry Authentication
nebula-plugins/nebula-docker-plugin pull request #10
Opened 2018-02-14 13:22 UTC by philippreston

This adds the ability to pass through username/password/email to the registryCredentials block in docker-java.  This feature is configured via the following:

Param | Description | Type | Default
-------|------------|-------|---------
dockerRepoAuth | Enable registryCredentials | boolean | false
dockerRepoUsername | The registry username | String | null
dockerRepoPassword | The registry password | String | null
dockerRepoEmail | The registry email | String | null

This is for use with our internal docker repo.

Many Thanks

2018-02-26 12:22 UTC, philippreston commented
Hey 

Just checking in on whether this is something that would be acceptable to merge in?  The plugin (including this change) is something I am keen to use in an active project.

Many thanks

Phil

2018-02-28 21:09 UTC, liviutudor commented
Hi Phil,

Just returning from a holiday, and looking into this today.

Thanks for your pull request.

2018-02-28 21:15 UTC, liviutudor requested changes
small addendum needed to the unit tests as per my comment in the review

2018-02-28 21:15 UTC, liviutudor commented on src/functionalTest/groovy/nebula/plugin/docker/NebulaDockerPluginTest.groovy
> +    def "enabling repoAuth and setting the username password and email on docker.registryCredentials"() {
can you also add a test to ensure that flipping the switch on `dockerRepoAuth` does NOT include the credentials?

2018-02-28 21:15 UTC, liviutudor commented on src/test/groovy/nebula/plugin/docker/NebulaDockerSensibleDefaultsTest.groovy
> +        !ext.dockerRepoAuth
+1 for thinking to add these here.

2018-03-01 10:28 UTC, philippreston commented
Hey Liviu

Thanks for that.  I have made the change and added an additional unit test for the flip on the dockerRepoAuth.

I've squashed the additional commit.

Many thanks for looking at this

Phil

2018-03-01 16:45 UTC, liviutudor approved these changes

2018-03-01 16:45 UTC, merged